import React, { useState } from "react";


const translations = {
  vi: {
    artists: "Nghệ sĩ",
    songs: "Bài hát",
    albums: "Album",
    genres: "Thể loại",
    playlists: "Playlist",
    home: "Trang Chủ",
    search: "Tìm Kiếm",
    playlist: "Danh Sách Phát",
    createPlaylist: "Tạo danh sách phát của bạn đầu tiên",
    easyHelp: "Thật dễ dàng, chúng tôi sẽ giúp bạn",
    createButton: "Tạo danh sách phát",
    findPodcast: "Tìm các podcast để theo dõi",
    updatePodcasts: "Chúng tôi sẽ cập nhật cho bạn về các tập mới",
    browseButton: "Duyệt podcast",
    legal: "Pháp lý",
    safety: "Trung Tâm An Toàn & Bảo Mật",
    privacy: "Chính Sách Bảo Mật",
    cookies: "Cookies",
    ads: "Về Quảng Cáo",
    accessibility: "Truy Cập",
    language: "Tiếng Việt",
    admin: "Quản trị",
    hello: "Xin chào",
    logout: "Đăng xuất",
    register: "Đăng ký",
    login: "Đăng nhập",
    myWebsite: "Trang web của tôi",
    allRightsReserved: "Đã đăng ký bản quyền",
    aboutUs: "Về chúng tôi",
    services: "Dịch vụ",
    contact: "Liên hệ",
    contactUs: "Liên hệ chúng tôi",
    phone: "Điện thoại",
    showAll: "Tất cả",
    popularArtist: "Nghệ Sĩ nổi tiếng",
    popularAlbum: "Những Album phổ biến",
    popularRadio: "Những Radio nỗi tiếng",
    username: "Tên người dùng",
    password: "Mật khẩu",
    confirm: "Xác nhận mật khẩu",
    have: "Bạn đã có tài khoản?",
    Dhave: "Bạn chưa có tài khoản?",
    Google: "Đăng nhập với Google",
    Facebook: "Đăng nhập với Facebook",
    requireUser: "Tên người dùng là bắt buộc!",
    requireUserLen: "Tên người dùng phải có nhiều hơn 3 ký tự!",
    requirePass: "Mật khẩu là bắt buộc!",
    requirePassLen: "Mật khẩu phải có độ dài ít nhất 6 ký tự!",
    requireEmail: "Email thì cần thiết!",
    invalidEmail: "Email không hợp lệ!",
    invalidLength: "Email phải có độ dài từ 20 đến 55 ký tự.",
    invalidChars: "Email chứa ký tự không hợp lệ",
    invalidDo: "Tên miền email không hợp lệ.",
    requireCPass: "Xác nhận mật khẩu.",
    requireCPassLen: "Tên miền email không hợp lệ.",
    requireCPassMatch: "Mật khẩu và mật khẩu xác nhận không khớp!",
    Remember: "Ghi nhớ",
    Forgot: "Quên mật khẩu?",
    Mess: "Nhập địa chỉ email hoặc tên người dùng của bạn và chúng tôi sẽ gửi cho bạn một liên kết để lấy lại quyền truy cập vào tài khoản của bạn.",
    Browse: "Duyệt tất cả",
    SearchRecent: "Tìm kiếm gần đây",
    GoBack: "Trở về",
    GoForward: "Tiếp theo",
    SearchQuery: "Kết quả tìm kiếm cho",
    TopResult: "Kết quả hàng đầu"
  },
  en: {
    artists: "Artists",
    songs: "Songs",
    albums: "Albums",
    genres: "Genres",
    playlists: "Playlists",
    home: "Home",
    search: "Search",
    playlist: "Playlist",
    createPlaylist: "Create your first playlist",
    easyHelp: "It's easy, we'll help you",
    createButton: "Create playlist",
    findPodcast: "Let's find some podcast to follow.",
    updatePodcasts: "We'll keep you updated on new episodes",
    browseButton: "Browse podcasts",
    legal: "Legal",
    safety: "Safety & Privacy Center",
    privacy: "Privacy Policy",
    cookies: "Cookies",
    ads: "About Ads",
    accessibility: "Accessibility",
    language: "English",
    admin: "Admin",
    hello: "Hello",
    logout: "Logout",
    register: "Register",
    login: "Login",
    myWebsite: "My Website",
    allRightsReserved: "All rights reserved",
    aboutUs: "About Us",
    services: "Services",
    contact: "Contact",
    contactUs: "Contact us",
    phone: "Phone",
    showAll: "Show all",
    popularArtist: "Popular artists",
    popularAlbum: "Popular albums",
    popularRadio: "Popular radios",
    username: "Username",
    password: "Password",
    confirm: "Confirm password",
    have: "Already have an account",
    Dhave: "Don't you have an account?",
    Google: "Sign up with Google",
    Facebook: "Sign up with Facebook",
    requireUser: "Username is required!",
    requireUserLen: "Username must be more than 3 characters!",
    requirePass: "Password is required!",
    requirePassLen: "Password must be at least 6 characters long!",
    requireEmail: "Email is required!",
    invalidEmail: "Invalid email!",
    invalidLength: "Email must be between 5 and 55 characters long.",
    invalidChars: "Email contains invalid characters",
    invalidDo: "Invalid email domain",
    requireCPass: "Confirm is required!",
    requireCPassLen: "Confirm password more than 6 characters!",
    requireCPassMatch: "Password and confirm password do not match!",
    Remember: "Remember Me",
    Forgot: "Forgot password?",
    Mess: "Enter your email address or username, and we'll send you a link to regain access to your account.",
    Browse: "Browse all",
    SearchRecent: "Recent searches",
    GoBack: "Go Back",
    GoForward: "Go Forward",
    SearchQuery: "Search results for",
    TopResult: "Top result"
  },
};

const LanguageContext = React.createContext({
  language: "vi",
  setLanguage: () => {},
  translations: translations.vi,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("vi");

  const switchLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: switchLanguage,
        translations: translations[language],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
